# Generated by Django 4.0.4 on 2022-05-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Phishing', models.BooleanField()),
                ('Medium', models.CharField(max_length=10)),
                ('Screenshot', models.ImageField(upload_to='')),
                ('URL', models.CharField(max_length=150)),
            ],
        ),
    ]
