# Generated by Django 4.0.4 on 2022-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=150)),
            ],
        ),
    ]
