# Generated by Django 4.0.4 on 2022-06-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='URL',
            new_name='answer',
        ),
    ]
