# Generated by Django 4.0.4 on 2022-11-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Screenshot',
            new_name='HtmlName',
        ),
    ]
