# Generated by Django 4.0.4 on 2022-11-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_rename_screenshot_question_htmlname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='HtmlName',
            new_name='Screenshot',
        ),
    ]
