# Generated by Django 4.0.4 on 2022-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_rename_htmlname_question_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Phishing', models.BooleanField()),
                ('Html_Name', models.CharField(max_length=150)),
                ('URL', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Phishing', models.BooleanField()),
                ('Html_Name', models.CharField(max_length=150)),
                ('URL', models.CharField(max_length=150)),
            ],
        ),
    ]
