# Generated by Django 4.0.4 on 2023-04-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_emails_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='CUTE',
            field=models.CharField(default='null', max_length=7),
            preserve_default=False,
        ),
    ]
